package codigo;
import java_cup.runtime.*;

/* Código interno del parser */
parser code {:
    public void syntax_error(Symbol s){
        System.err.println("Error sintactico en linea " + (s.left+1) + " col " + (s.right+1) + ". Token: " + s.value);
    }
:};

/* Terminales (Tokens que vienen del Lexer JHVHJALY) */
terminal ENTERO, IGUAL, SUMA, RESTA, MULT, DIV, PUNTO_COMA;
terminal Integer NUMERO;
terminal String ID, CADENA;

/* No Terminales */
non terminal Object inicio, instruccion, expresion;

/* Precedencia de operaciones */
precedence left SUMA, RESTA;
precedence left MULT, DIV;

start with inicio;

/* Reglas Gramaticales */
inicio ::= instruccion 
        | inicio instruccion 
        ;

/* Estructura: LTALYV variable ~ valor ^ */
instruccion ::= ENTERO ID:i IGUAL expresion:e PUNTO_COMA
    {: System.out.println("LOGRADO: '" + i + "' tiene el valor -> " + e); :}
    ;

expresion ::= expresion:e1 SUMA  expresion:e2   {: RESULT = (Integer)e1 + (Integer)e2; :}
            | expresion:e1 RESTA expresion:e2   {: RESULT = (Integer)e1 - (Integer)e2; :}
            | expresion:e1 MULT  expresion:e2   {: RESULT = (Integer)e1 * (Integer)e2; :}
            | expresion:e1 DIV   expresion:e2   {: RESULT = (Integer)e1 / (Integer)e2; :}
            | NUMERO:n                          {: RESULT = n; :}
            | CADENA:c                          {: RESULT = c; :}
            | ID:i                              {: RESULT = i; :} 
            ;
