package codigo;
import java_cup.runtime.*;

/* DEBE decir 'parser code', no el nombre de tu archivo */
parser code {:
    public void syntax_error(Symbol s){
        System.err.println("Error sintactico en linea " + (s.left+1) + " col " + (s.right+1) + ". Token: " + s.value);
    }
:};

/* Terminales */
terminal ENTERO, IGUAL, SUMA, RESTA, MULT, DIV, PUNTO_COMA;
terminal Integer NUMERO;
terminal String ID;

/* No Terminales */
non terminal Object inicio, instruccion, expresion;

/* Precedencia */
precedence left SUMA, RESTA;
precedence left MULT, DIV;

start with inicio;

inicio ::= instruccion 
        | inicio instruccion 
        ;

instruccion ::= ENTERO ID:i IGUAL expresion:e PUNTO_COMA
    {: System.out.println("EXITO:  '" + i + "' ~ " + e); :}
    ;

expresion ::= expresion:e1 SUMA expresion:e2    {: RESULT = (Integer)e1 + (Integer)e2; :}
            | expresion:e1 RESTA expresion:e2   {: RESULT = (Integer)e1 - (Integer)e2; :}
            | expresion:e1 MULT expresion:e2    {: RESULT = (Integer)e1 * (Integer)e2; :}
            | expresion:e1 DIV expresion:e2     {: RESULT = (Integer)e1 / (Integer)e2; :}
            | NUMERO:n                          {: RESULT = n; :}
            | ID:i                              {: RESULT = 0; :} 
            ;