
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJflex;

import java_cup.runtime.*;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class LTALYVCUP extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public LTALYVCUP() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public LTALYVCUP(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public LTALYVCUP(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\003\000\002\002" +
    "\004\000\002\003\007\000\002\004\005\000\002\004\005" +
    "\000\002\004\005\000\002\004\005\000\002\004\003\000" +
    "\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\004\004\005\001\002\000\006\002\000\004" +
    "\000\001\002\000\004\014\011\001\002\000\006\002\010" +
    "\004\005\001\002\000\006\002\uffff\004\uffff\001\002\000" +
    "\004\002\001\001\002\000\004\005\012\001\002\000\006" +
    "\013\014\014\013\001\002\000\014\006\ufff8\007\ufff8\010" +
    "\ufff8\011\ufff8\012\ufff8\001\002\000\014\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\001\002\000\014\006\021\007" +
    "\016\010\017\011\022\012\020\001\002\000\006\013\014" +
    "\014\013\001\002\000\006\013\014\014\013\001\002\000" +
    "\006\002\ufffe\004\ufffe\001\002\000\006\013\014\014\013" +
    "\001\002\000\006\013\014\014\013\001\002\000\014\006" +
    "\ufffa\007\ufffa\010\ufffa\011\ufffa\012\ufffa\001\002\000\014" +
    "\006\ufffd\007\ufffd\010\017\011\022\012\ufffd\001\002\000" +
    "\014\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\001\002" +
    "\000\014\006\ufffc\007\ufffc\010\017\011\022\012\ufffc\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\014\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\025\001\001\000\004\004\024\001" +
    "\001\000\002\001\001\000\004\004\023\001\001\000\004" +
    "\004\022\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$LTALYVCUP$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$LTALYVCUP$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$LTALYVCUP$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){
        System.err.println("Error sintactico en linea " + (s.left+1) + " col " + (s.right+1) + ". Token: " + s.value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$LTALYVCUP$actions {
  private final LTALYVCUP parser;

  /** Constructor */
  CUP$LTALYVCUP$actions(LTALYVCUP parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$LTALYVCUP$do_action_part00000000(
    int                        CUP$LTALYVCUP$act_num,
    java_cup.runtime.lr_parser CUP$LTALYVCUP$parser,
    java.util.Stack            CUP$LTALYVCUP$stack,
    int                        CUP$LTALYVCUP$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$LTALYVCUP$result;

      /* select the action based on the action number */
      switch (CUP$LTALYVCUP$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).value;
		RESULT = start_val;
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$LTALYVCUP$parser.done_parsing();
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= instruccion 
            {
              Object RESULT =null;

              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= inicio instruccion 
            {
              Object RESULT =null;

              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instruccion ::= ENTERO ID IGUAL expresion PUNTO_COMA 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-3)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-1)).value;
		 System.out.println("EXITO:  '" + i + "' ~ " + e); 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-4)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = (Integer)e1 + (Integer)e2; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expresion ::= expresion RESTA expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = (Integer)e1 - (Integer)e2; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expresion ::= expresion MULT expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = (Integer)e1 * (Integer)e2; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expresion ::= expresion DIV expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = (Integer)e1 / (Integer)e2; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.elementAt(CUP$LTALYVCUP$top-2)), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expresion ::= NUMERO 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = n; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expresion ::= ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LTALYVCUP$stack.peek()).value;
		 RESULT = 0; 
              CUP$LTALYVCUP$result = parser.getSymbolFactory().newSymbol("expresion",2, ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), ((java_cup.runtime.Symbol)CUP$LTALYVCUP$stack.peek()), RESULT);
            }
          return CUP$LTALYVCUP$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$LTALYVCUP$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$LTALYVCUP$do_action(
    int                        CUP$LTALYVCUP$act_num,
    java_cup.runtime.lr_parser CUP$LTALYVCUP$parser,
    java.util.Stack            CUP$LTALYVCUP$stack,
    int                        CUP$LTALYVCUP$top)
    throws java.lang.Exception
    {
              return CUP$LTALYVCUP$do_action_part00000000(
                               CUP$LTALYVCUP$act_num,
                               CUP$LTALYVCUP$parser,
                               CUP$LTALYVCUP$stack,
                               CUP$LTALYVCUP$top);
    }
}

}
