
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJflex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 11;
  public static final int SUMA = 4;
  public static final int PUNTO_COMA = 8;
  public static final int MULT = 6;
  public static final int ENTERO = 2;
  public static final int EOF = 0;
  public static final int NUMERO = 9;
  public static final int ID = 10;
  public static final int DIV = 7;
  public static final int IGUAL = 3;
  public static final int error = 1;
  public static final int RESTA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "IGUAL",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "PUNTO_COMA",
  "NUMERO",
  "ID",
  "CADENA"
  };
}

